### ISSUE TITLE
Disable cache expiry

### ISSUE THREAD

**Issue by Jarlskov** [andywer/laravel-js-localization#29]
We use js-localization (thanks :-)) in a Laravel 5.1 project, and it's working really well.

We do have one issue, though, I believe it's to do with the cache.
Some of the longest running processes on our site is /js-localization/messages . My guess is that it's because the message cache expires and the messages json is rebuilt. Is it possible to disable the cache expiry and only have the messages rebuilt using the artisan command? Or did I misunderstand what is actually going on in that step? :-)

**Comment by andywer** [comment]
Hi @Jarlskov!

Interesting point, but I fear there must be another cause. Cache expiry can't be it I think, since the it's cached using `Cache::forever`: https://github.com/andywer/laravel-js-localization/blob/laravel-5/src/Caching/AbstractCachingService.php#L64

Maybe you can further investigate that for your use case, like:
- is it permanently slow or just occasionally
- do you use a fast caching provider
- how does disabling the message cache affect performance (just monkeypatch the code)

Hope that helps.

**Comment by Jarlskov** [comment]
Hej @andywer 

Thanks for the reply.
It makes sense, so the issue probably is that we're currently just using the disk as a cache, so disk IO is the load time. It just seems strange that it would be that much slower than basically any other request, but that might just be a local issue in our setup.
I should probably look into having some proper caching mechanism set up.

**Comment by andywer** [comment]
Any news on that @Jarlskov?

**Comment by Jarlskov** [comment]
Not yet, @andywer , I'm still on the issue. We just had some larger server issues and had to do a pretty panicky server change so I want to make sure that everything runs smoothly before I change too much in our setup :-)
My plan is to change between Christmas and New Year.

**Comment by Jarlskov** [comment]
I've moved to using Redis as a cache now, and most of it seems pretty good. We do still see a few spikes where the request takes a long time. We have a request about 15 min ago where New Relic reported the slowest component to be `	/\JsLocalization\Http\Controllers\JsLocalizationController@createJsMessages` taking 60 sec

**Comment by andywer** [comment]
Hmm, no clue. Maybe there is a chance that the Redis cache item expires (even though `Cache::forever()` is used) or that there are problems with the Redis connection from time to time?

I guess you use that cache for other things than localizations as well and it works perfectly fine then?

**Comment by Jarlskov** [comment]
Me neither, I just wanted to keep you updated on the current state, even though you of course can't help much with whatever limited info I can currently provide :-)
I'll keep an eye on it, and see if anything of interest pops up.

**Comment by Jarlskov** [comment]
I've looked a bit more into it, and it seems like one issue is that we always hit a PHP endpoint. This means that Apache can't cache it properly and we need to boot Laravel all of the time.
Do you think it would be a good idea to allow saving the generated JS to a file?
Making it a static file should make it easier to use caching headers, and it would allow us to include it in our JS compilation flow, and maybe even minify it, and version it to provide cache invalidation.
It could probably be made as an optional setting, to allow backwards compatibility.
Do you think this would be a good approach? Then it should probably be possible for me to create a PR to add the feature, if you'd include it in the project.

**Comment by andywer** [comment]
Hey @Jarlskov. Thanks for the update :)

Yeah, actually I think any decent, up-to-date library for exporting the translations should be able to create static files, also because many people will want to bundle it with their other JS sources (#21).

Unfortunately I don't have the time right now and my interest in writing PHP code is near zero 🙈
But if you open a PR I will review it :)
