### ISSUE TITLE
Empty Messages

### ISSUE THREAD

**Issue by FFXV** [andywer/laravel-js-localization#34]
I am using Laravel 5.3.

I installed and set up the package as instructed.

However, no translations are available. Browsing to /js-localization/messages shows Lang.addMessages({"fr":[],"en":[]});

Anything I still have to do in addition to what is said in the README?

My paths look like e.g. ..lang/en/auth.php. Standard, I assume.

Maybe I should say that I also have mcamara's localization package installed.

**Comment by andywer** [comment]
Hey @FFXV.

Sorry, but this might be an issue with your local setup and I don't know the other localization package you mentioned.

If you set the `messages` to export and run `php artisan js-localization:refresh` it should work.

**Comment by carestad** [comment]
Also sounds like it could be a caching issue. If you are running a dev environment with Vagrant or something of the like, and use Memcached, you need to issue the artisan commands within your virtual instance. Or possible make use of caching to files instead of memcached for your development environment :)
